### ISSUE TITLE
"UnexpectedPrimitive { expected: "Stream", found: "Array" }" error on git master

### ISSUE THREAD

**Issue by markcatley** [pdf-rs/pdf#90]
I am trying to open a PDF and am getting the following error:
```
Error: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/file.rs", line: 94, column: 19, source: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/object/types.rs", line: 22, column: 42, source: FromPrimitive { typ: "Option < Content >", field: "contents", source: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/content.rs", line: 469, column: 28, source: UnexpectedPrimitive { expected: "Stream", found: "Array" } } } } }
```
I am using git master (390fec1).
Any suggestions? It's a public PDF that I've downloaded off the internet, however, the fact that I'm looking at it is private. I can provide the PDF or a link privately if that would help.

EDITED: Sorry, I made an error when posting the original issue. I was reading and writing to the same file by mistake. I've updated this post with the correct error, the original error is below if anyone is interested.
```
Error: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/file.rs", line: 194, column: 24, source: Other { msg: "file header is missing" } }
```

**Comment by divergentdave** [comment]
I'll bite, I think I touched that code last. Looks like either we are being too strict parsing the %PDF-1.x header, or the file is malformed. Please send me a link at divergentdave@gmail.com.

**Comment by markcatley** [comment]
Erg, sorry, I think the problem was I was accidentally reading to and writing the output to the same file. I downloaded the PDF again and I'm getting a new error.
```
Error: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/file.rs", line: 94, column: 19, source: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/object/types.rs", line: 22, column: 42, source: FromPrimitive { typ: "Option < Content >", field: "contents", source: Try { file: "/Users/markcatley/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/390fec1/pdf/src/content.rs", line: 469, column: 28, source: UnexpectedPrimitive { expected: "Stream", found: "Array" } } } } }
```
@divergentdave I'll email you the PDF anyway.

**Comment by divergentdave** [comment]
I looked at the source of the error, and what I see is that in `<Content as Object>::from_primitive`, there is a match on the given primitive that either handles looping over arrays or otherwise passes the primitive on to `<ContentStream as Object>::from_primitive`. In this PDF file, the primitive is almost always a `Primitive::Reference`, and the first time the reference points to an array, `<ContentStream as Object>::from_primitive` chokes on it.

The PDF reference says that `/Contents` may be a stream or array of streams, and it is silent on the question of direct versus indirect objects. `/Contents` being an indirect object reference for an array is conformant, and we'll need to change this function to handle that case.

I think we need to call resolve on p before checking whether to use the special array handling logic. I'll give this a try and see if that fixes the issue.

**Comment by divergentdave** [comment]
The next issues I run into with this file are due to as-yet unsupported color space types. From running the read example, I get `"found a function stream with type Some(Integer(0))"`, and from pdf_render, I get that `ColorSpace::Pattern` is not supported by the renderer.

**Comment by markcatley** [comment]
Thanks @divergentdave, I'm not trying to render the PDF, I'm trying to extract and analyse the text so 🤞 this will be enough for me. I'll check it out and let you know.

**Comment by markcatley** [comment]
👍 I now get the error you talked about. I'll raise another issue for that.
